### ISSUE TITLE
App not installed

### ISSUE THREAD

**Issue by KarmaMod** [kikfox/kikfox#8]
I'm having issues getting this game to install without any changes. First i'm getting `Failure [INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]`.

After removing `android:isSplitRequired="true"`, `android:extractNativeLibs="false"` and change sdk to `targetSdkVersion: '29'`, I'm getting different error `Failure [INSTALL_FAILED_VERIFICATION_FAILURE]`. I have zipalign and signed the APK

APK file:
https://apkcombo.com/a-ka-xia-ji-hua/com.kunyue.ecyakxjh/download/apk
https://apkcombo.com/three-kingdoms-heroes-of-legend/com.mh.dgqs.android/download/apk

**Comment by kikfox** [comment]
Not related to compiling/decompiling, I think you need to check `android:extractNativeLibs` in the `application` tag of AndroidManifest.xml

**Comment by KarmaMod** [comment]
That's what i did.

I figured out I needed the -f flag for zipalign `zipalign.exe -f -p 4 "aaaad.apk" "aaaad zipalign.apk"`

Now I got another issue. App icon is default, and app crashes

```
02-05 17:22:36.381 E/AndroidRuntime( 4562): FATAL EXCEPTION: main
02-05 17:22:36.381 E/AndroidRuntime( 4562): Process: com.mh.dgqs.android, PID: 4562
02-05 17:22:36.381 E/AndroidRuntime( 4562): java.lang.Error: FATAL EXCEPTION [main]
02-05 17:22:36.381 E/AndroidRuntime( 4562): Unity version     : 2017.4.29f1
02-05 17:22:36.381 E/AndroidRuntime( 4562): Device model      : samsung SM-G988N
02-05 17:22:36.381 E/AndroidRuntime( 4562): Device fingerprint: samsung/z3qksx/z3q:7.1.2/NRD90M/700210731:user/release-keys
02-05 17:22:36.381 E/AndroidRuntime( 4562): 
02-05 17:22:36.381 E/AndroidRuntime( 4562): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at com.unity3d.player.j.onLayout(Unknown Source)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.View.layout(View.java:17638)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.View.layout(View.java:17638)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.View.layout(View.java:17638)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.View.layout(View.java:17638)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:727)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.View.layout(View.java:17638)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.Choreographer.doFrame(Choreographer.java:621)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.os.Handler.handleCallback(Handler.java:751)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.os.Looper.loop(Looper.java:154)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at android.app.ActivityThread.main(ActivityThread.java:6176)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at java.lang.reflect.Method.invoke(Native Method)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
02-05 17:22:36.381 E/AndroidRuntime( 4562): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
02-05 17:22:36.384 W/ActivityManager( 2125):   Force finishing activity com.mh.dgqs.android/com.mihua.body.UnityActivity
```
